version: '2'

services:
    web:
        build: ./
        ports:
            - "8000:80"
        links:
            - db:db
        volumes:
            - ./www:/var/www/html
        restart: always
    db:
        image: mysql:5.7
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
        restart: always
    myadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        links:
            - db:db
        restart: always