version: 2

jobs:
  check-php-cs:
    docker:
      - image: circleci/php:7.1-node-browsers
    steps:
      - checkout
      - run:
          name: Install PHP CS Fixer
          command: wget https://cs.sensiolabs.org/download/php-cs-fixer-v2.phar -O php-cs-fixer
      - run:
          name: Check PHP CS
          command: php php-cs-fixer fix --dry-run --allow-risky yes --diff --config=.php_cs

workflows:
  version: 2
  check_and_tests:
    jobs:
      - check-php-cs